name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04  # Use a specific version for stability
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Using Zulu as the distribution of Java
          java-version: 8
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2
      
      - name: Build with Maven
        run: mvn clean package
      
      - name: Upload WAR file
        uses: actions/upload-artifact@v4
        with:
          name: verademo.war
          path: target/verademo.war

  pipeline_scan:
      needs: build
      runs-on: ubuntu-latest
      name: pipeline scan
      steps:
        - name: checkout repo
          uses: actions/checkout@v3

        - name: get archive
          uses: actions/download-artifact@v4
          with:
            name: verademo.war
        - name: pipeline-scan action step
          id: pipelien-scan
          uses: veracode/Veracode-pipeline-scan-action@v1.0.15
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            #file: "auth.js.zip"
            file: "verademo.war" 
            #request_policy: "VeraDemo Policy"
            #store_baseline_file: true
            #store_baseline_file_branch: "feature-123"
            #create_baseline_from: "standard"
            debug: 0
            fail_build: false

# This step will import flaws from the step above
  import-pipeline-flaws:
    needs: pipeline_scan
    runs-on: ubuntu-latest
    steps:
      - name: get flaw file
        uses: actions/download-artifact@v3
        with:
          name: Veracode Pipeline-Scan Results
          path: /tmp

      - name: import flaws as issues
        uses: veracode/veracode-flaws-to-issues@v2.2.24
        with:
          scan-results-json: '/tmp/filtered_results.json'
