name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04  # Use a specific version for stability
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Using Zulu as the distribution of Java
          java-version: 8
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2
      
      - name: Build with Maven
        run: mvn clean package
      
      - name: Upload WAR file
        uses: actions/upload-artifact@v4
        with:
          name: verademo.war
          path: target/verademo.war
